name: Release

on:
  create:
    ref_type: tag

jobs:
  release:
    name: release / ${{ matrix.browser }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
      - name: Git
        run: git config --global url."https://github.com/".insteadOf git://github.com/

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install --production

      - name: Build (${{ matrix.browser }})
        run: yarn build:${{ matrix.browser }}

      - name: Zip
        run: yarn zip

      - name: Release (Firefox)
        uses: trmcnvn/firefox-addon@v1
        if: matrix.browser == 'firefox'
        with:
          uuid: "{6c337925-991d-4139-8b64-8380cd30517a}"
          xpi: arconnect.zip
          manifest: public/manifest.json
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}

      - name: Release (Chrome)
        uses: Klemensas/chrome-extension-upload-action@master
        if: matrix.browser == 'chrome'
        with:
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          file-name: arconnect.zip
          app-id: einnioafmpimabjcddiinlhmijaionap
          publish: true
